# -*- mode: Python -*-
# allow_k8s_contexts('rancher-desktop')

# to disable push with rancher desktop we need to use custom_build instead of docker_build
# docker_build('green-enterprise-golang', '.', dockerfile='Dockerfile')
custom_build('green-enterprise-golang', 'docker build -t $EXPECTED_REF .', ['./'], disable_push=True)

k8s_yaml(kustomize('./k8s/'))
k8s_resource(workload='green-enterprise-golang', port_forwards=[port_forward(18080, 8080, 'HTTP API')], labels=['Golang'])
