apiVersion: v1
kind: Service
metadata:
  name: green-enterprise-java
  labels:
    type: microservice
spec:
  selector:
    app: green-enterprise-java
  type: ClusterIP
  sessionAffinity: None
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
